"""add_response_schema_to_integrationoperation
Revision ID: 017449baaf0e
Revises: 342a4a6e3c62
Create Date: 2026-05-04 21:00:23.452956
"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017449baaf0e'
down_revision: Union[str, Sequence[str], None] = '342a4a6e3c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrationoperation', sa.Column('response_schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrationoperation', 'response_schema')
    # ### end Alembic commands ###
