"""add knowledge and agent config models
Revision ID: 08c69195d80c
Revises: 48e85a23006d
Create Date: 2026-05-03 22:35:39.445412
"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '08c69195d80c'
down_revision: Union[str, Sequence[str], None] = '48e85a23006d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgvector extension is enabled
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentconfiguration',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('fallback_rule', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentconfiguration_workspace_id'), 'agentconfiguration', ['workspace_id'], unique=True)
    op.create_table('knowledgesource',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgesource_file_key'), 'knowledgesource', ['file_key'], unique=False)
    op.create_index(op.f('ix_knowledgesource_name'), 'knowledgesource', ['name'], unique=False)
    op.create_index(op.f('ix_knowledgesource_workspace_id'), 'knowledgesource', ['workspace_id'], unique=False)
    op.create_table('documentchunk',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledgesource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentchunk_source_id'), 'documentchunk', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentchunk_source_id'), table_name='documentchunk')
    op.drop_table('documentchunk')
    op.drop_index(op.f('ix_knowledgesource_workspace_id'), table_name='knowledgesource')
    op.drop_index(op.f('ix_knowledgesource_name'), table_name='knowledgesource')
    op.drop_index(op.f('ix_knowledgesource_file_key'), table_name='knowledgesource')
    op.drop_table('knowledgesource')
    op.drop_index(op.f('ix_agentconfiguration_workspace_id'), table_name='agentconfiguration')
    op.drop_table('agentconfiguration')
    # ### end Alembic commands ###
