"""add_integration_models
Revision ID: 342a4a6e3c62
Revises: 7af73d5e7f4f
Create Date: 2026-05-04 18:46:36.995980
"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342a4a6e3c62'
down_revision: Union[str, Sequence[str], None] = '7af73d5e7f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=True),
    sa.Column('spec_url', sa.Text(), nullable=True),
    sa.Column('spec_content', sa.JSON(), nullable=True),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('auth_header_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_name'), 'integration', ['name'], unique=False)
    op.create_index(op.f('ix_integration_workspace_id'), 'integration', ['workspace_id'], unique=False)
    op.create_table('integrationoperation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters_schema', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrationoperation_integration_id'), 'integrationoperation', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integrationoperation_operation_id'), 'integrationoperation', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrationoperation_operation_id'), table_name='integrationoperation')
    op.drop_index(op.f('ix_integrationoperation_integration_id'), table_name='integrationoperation')
    op.drop_table('integrationoperation')
    op.drop_index(op.f('ix_integration_workspace_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_name'), table_name='integration')
    op.drop_table('integration')
    # ### end Alembic commands ###
