"""add unique constraint to user organization_id and rename website field
Revision ID: 48e85a23006d
Revises: 692c9c28ca68
Create Date: 2026-05-03 21:15:30.804461
"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48e85a23006d"
down_revision: Union[str, Sequence[str], None] = "692c9c28ca68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column("organization", "website_url")
    op.create_unique_constraint(None, "user", ["organization_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.add_column("organization", sa.Column("website_url", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("organization", "website")
    # ### end Alembic commands ###
