"""add timezone to workspace
Revision ID: 692c9c28ca68
Revises: 21e5d0a823f5
Create Date: 2026-05-03 03:12:37.153779
"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "692c9c28ca68"
down_revision: Union[str, Sequence[str], None] = "21e5d0a823f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "timezone")
    # ### end Alembic commands ###
