"""add workspace_id to session
Revision ID: 7af73d5e7f4f
Revises: 08c69195d80c
Create Date: 2026-05-04 01:08:36.120068
"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af73d5e7f4f'
down_revision: Union[str, Sequence[str], None] = '08c69195d80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable first
    op.add_column('session', sa.Column('workspace_id', sa.Integer(), nullable=True))
    
    # 2. Update existing sessions with a workspace_id from the user's organization
    op.execute(
        """
        UPDATE session 
        SET workspace_id = (
            SELECT w.id 
            FROM workspace w 
            JOIN "user" u ON u.organization_id = w.org_id 
            WHERE u.id = session.user_id 
            LIMIT 1
        )
        """
    )
    
    # 3. Set to NOT NULL after population
    op.alter_column('session', 'workspace_id', nullable=False)
    
    op.create_index(op.f('ix_session_workspace_id'), 'session', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'session', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_index(op.f('ix_session_workspace_id'), table_name='session')
    op.drop_column('session', 'workspace_id')
    # ### end Alembic commands ###
