"""add_widget_config_and_session_source
Revision ID: 841e34589fdf
Revises: 017449baaf0e
Create Date: 2026-05-05 01:15:42.574965
"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '841e34589fdf'
down_revision: Union[str, Sequence[str], None] = '017449baaf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_config',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('widget_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allowed_origins', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('welcome_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('placeholder_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lead_capture_enabled', sa.Boolean(), nullable=False),
    sa.Column('lead_capture_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='["email"]', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widget_config_widget_key'), 'widget_config', ['widget_key'], unique=True)
    op.create_index(op.f('ix_widget_config_workspace_id'), 'widget_config', ['workspace_id'], unique=True)
    op.add_column('session', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='dashboard'))
    op.alter_column('session', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('session', 'source')
    op.drop_index(op.f('ix_widget_config_workspace_id'), table_name='widget_config')
    op.drop_index(op.f('ix_widget_config_widget_key'), table_name='widget_config')
    op.drop_table('widget_config')
    # ### end Alembic commands ###
